# Autogenerated wrapper script for agg_jll for x86_64-w64-mingw32
export agg

JLLWrappers.@generate_wrapper_header("agg")
JLLWrappers.@declare_executable_product(agg)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        agg,
        "bin\\agg.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
